# Q8.Tumhare pass four employes ki details hai list mai:-
# Code Example
# import json
# a=["neelam","programer","24","2400",]
# b=["komal","trainer","24","20000"]
# c=["anuradha","HR","25","40000"]
# d=["Abhishek","manager","29","63000"]
# keys=["name","desigin","age","selary"]
# emp1={}
# emp2={}
# emp3={}
# emp4={}
# dict1={"emp1":emp1,"emp2":emp2,"emp3":emp3,"emp4":emp4}
# for i in range(len(a)):
#   emp1.update({keys[i]:a[i]})
# for j in range(len(b)):
#   emp2.update({keys[j]:b[j]}) 
# for k in range(len(c)):
#   emp3.update({keys[k]:c[k]})
# for l in range(len(d)):
#   emp4.update({keys[l]:d[l]}) 
# with open("question 8.json","w")as g:
#   json.dump(dict1,g,indent=2)  
    




# # { 
# #   "emp1":{ "name":"nilam",
# #   "Designation":"programmer",
# #   "Age":"34",
# #     "salary":"24000",
# #   },
  

# #   "emp2":{ "name":"komal",
# #   "Designation":"Trainee",
# #   "Age":"24",
# #   "salary":"20000",

# #   },

 
# #   "emp3":{ "name":"anuradha",
# #   "Designation":"HR",
# #   "Age":"25",
# #   "salary":"40000",
# #   },


# #   "emp4":{ "name":"Abhishek",
# #   "Designation":"Manager",
# #   "Age":"29",
# #   }
# # }
  



